---
driver_plugin: ec2
driver_config:
  require_chef_omnibus: true
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_EC2_KEYPAIR'] %>
  ssh_key: <%= ENV['AWS_EC2_KEYPASS'] %>

platforms:
- name: amazon-linux-small-tokyo
  driver_config:
    username: ec2-user
    flavor_id: m1.small
    image_id: ami-3561fe34 # Amazon Linux AMI 2013.09.1
    region: ap-northeast-1
    availability_zone: ap-northeast-1a
    tags:
      Name: test-kitchen-small

suites:
  - name: basercms
    run_list:
      - recipe[basercms::default]
    attributes:
