---
driver_plugin: ec2
driver_config:
  require_chef_omnibus: true
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_EC2_KEYPAIR'] %>
  ssh_key: <%= ENV['AWS_EC2_KEYPATH'] %>

platforms:
- name: amazon-linux-small-tokyo
  driver_config:
    username: ec2-user
    flavor_id: m1.small
    image_id: <%= ENV['AWS_AMI'] %>
    region: <%= ENV['AWS_REGION'] %>
    availability_zone: <%= ENV['AWS_AZ'] %>
    tags:
      Name: test-kitchen-small

suites:
  - name: basercms
    run_list:
      - recipe[basercms::default]
    attributes:
